version: 0.1.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  Config: Release+Release%203.5
hosts:
  hook.slack.com: 127.0.0.1
before_build:
- cmd: nuget restore src/Slack.Webhooks.sln
build:
  project: AppVeyor.csproj
  verbosity: minimal
after_build:
- ps: nuget pack .\src\Slack.Webhooks\Slack.Webhooks.nuspec -Version $env:APPVEYOR_BUILD_VERSION
artifacts:
- path: '*.nupkg'
- path: '*.nuspec'
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: webhooks
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true